### ISSUE TITLE
Configuración de Cuenta

### ISSUE THREAD

**Issue by wp-wilsonperez** [wp-wilsonperez/frontendInstances#112]
Estimado Juan al acceder a Configuración de Cuenta hay cosas que verificar porque no me estan funcionando.

Estatus Maritales -> cambiar pro Estado Civil
otra cosas al borrar si me quita del listado pero al intentar agregar no lo hace 
![image](https://user-images.githubusercontent.com/25553072/31452768-8d67e2de-ae75-11e7-8a6e-cf8e0f42f853.png)

IVA.- no lo esta sacando el por default

Y al intentar rellenar el resto de datos y guardar me da error de MACid

![image](https://user-images.githubusercontent.com/25553072/31452856-c4ebce78-ae75-11e7-83d2-68892a02a3cb.png)

**Comment by juanshot** [comment]
lo de guardar status maritales , el problema era los privilegios por default donde no estaba save

**Comment by juanshot** [comment]
consulta de mac daba error porque fue cambiado el id que se usaba

**Comment by wp-wilsonperez** [comment]
si amigo pero debería decir usted no tiene privilegios o no puede crear
